---
apiVersion: v1
kind: Namespace
metadata:
  name: rhbk
  labels:
    kubernetes.io/metadata.name: rhbk
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    openshift.io/display-name: RHDH demo project
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: rhbk-group
  namespace: rhbk
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  targetNamespaces:
    - rhbk
...
