---
apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: demo-keycloak-instance
  namespace: rhbk
  labels:
    app: sso
spec:
  http:
    httpEnabled: true
    httpPort: 8090
    tlsSecret: my-tls-secret
  hostname:
    adminUrl: 'https://keycloak-rhdh-operator.apps.cluster-9gppl.9gppl.sandbox2540.opentlc.com' #change to your route URL
    hostname: keycloak-rhdh-operator.apps.cluster-9gppl.9gppl.sandbox2540.opentlc.com
  instances: 1
  db:
    vendor: postgres
    host: keycloak-postgres
    usernameSecret:
      name: keycloak-db-secret
      key: username
    passwordSecret:
      name: keycloak-db-secret
      key: password
...
