apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: rhdh-realm
  namespace: rhbk
spec:
  keycloakCRName: demo-keycloak-instance
  realm:
    id: rhdh
    realm: rhdh
    displayName: "RHDH Authentication Realm"
    enabled: true
    identityProviders:
      - alias: GitLab
        displayName: GitLab
        enabled: true
        trustEmail: true
        firstBrokerLoginFlowAlias: first broker login
        config:
          authorizationUrl: 'https://gitlab.apps.cluster-9gppl.9gppl.sandbox2540.opentlc.com/oauth/authorize'
          clientAuthMethod: client_secret_basic
          clientId: 440b385244b0776cd2e95c6acec50bca2ed961276f137f486e3c4970a67a68e2
          clientSecret: gloas-gloas-cbc3d4d5ce5539e762b9064ed5fa7fa79a1dfb3ed99ff93cfbcd90910ebcc1c2
          syncMode: IMPORT
          tokenUrl: 'https://gitlab.apps.cluster-9gppl.9gppl.sandbox2540.opentlc.com/oauth/token'
          useJwksUrl: 'true'
        providerId: oidc
    clients:
      - clientAuthenticatorType: client-secret
        redirectUris:
          - "https://rhdh.apps.cluster-9gppl.9gppl.sandbox2540.opentlc.com/oauth2/callback"
        serviceAccountsEnabled: true
        clientId: rhdh
        defaultClientScopes:
          - profile
          - email
          - roles
        implicitFlowEnabled: false
        publicClient: false
        standardFlowEnabled: true
        name: rhdh
        description: Red Hat Developer Hub Client
        enabled: true
        scopeMappings: {}
        serviceAccountClientRoles:
          realm-management:
            - query-groups
            - query-users
            - view-users
...