---
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: rhdh-realm
  namespace: demo-project
spec:
  keycloakCRName: demo-keycloak-instance
  realm:
    id: rhdh
    realm: rhdh
    displayName: "RHDH Realm"
    enabled: true
    identityProviders:
      - alias: github
        displayName: "GitHub"
        providerId: github
        enabled: true
        trustEmail: true
        storeToken: false
        addReadTokenRoleOnCreate: false
        authenticateByDefault: false
        linkOnly: false
        firstBrokerLoginFlowAlias: first broker login
        config:
          clientId: "Ov23liFx1wJH03KaCmdj"
          clientSecret: "179c9ebe4cf7284e2b84e0660fd9db07142a196a"
          defaultScope: "user:email"
    clients:
      - clientId: rhdh
        name: rhdh
        description: Red Hat Developer Hub Client
        enabled: true
        protocol: openid-connect
        publicClient: false
        redirectUris:
          - "https://rhdh.apps.cluster-6fncd.6fncd.sandbox404.opentlc.com/api/auth/*"
        rootUrl: "https://rhdh.apps.cluster-6fncd.6fncd.sandbox404.opentlc.com"
        adminUrl: "https://rhdh.apps.cluster-6fncd.6fncd.sandbox404.opentlc.com"
        baseUrl: "https://rhdh.apps.cluster-6fncd.6fncd.sandbox404.opentlc.com"
        webOrigins:
          - "+"
        secret: "developer-hub-secret"
        standardFlowEnabled: true
        implicitFlowEnabled: false
        directAccessGrantsEnabled: false
        serviceAccountsEnabled: false
        authorizationServicesEnabled: false
...


apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: backstage
  namespace: rhsso
  finalizers:
    - client.cleanup
  labels:
    app: backstage
spec:
  client:
    clientAuthenticatorType: client-secret
    redirectUris:
      - 'https://backstage-backstage.apps.cluster-db5dk.db5dk.sandbox2071.opentlc.com/oauth2/callback'
    serviceAccountsEnabled: true
    clientId: backstage
    defaultClientScopes:
      - profile
      - email
      - roles
    implicitFlowEnabled: false
    publicClient: false
    standardFlowEnabled: true
    id: 773ab2fe-fa15-4f35-a85a-2e8117178c2c
    directAccessGrantsEnabled: true
  realmSelector:
    matchLabels:
      app: backstage
  scopeMappings: {}
  serviceAccountClientRoles:
    realm-management:
      - query-groups
      - query-users
      - view-users