---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config-rhdh
  namespace: demo-project
data:
  app-config.yaml: |
    app:
      title: Red Hat Developer Hub
      baseUrl: https://rhdh.apps.cluster-6fncd.6fncd.sandbox404.opentlc.com
    backend:
      auth:
        keys:
          - secret: ${BACKEND_SECRET}
      baseUrl: https://rhdh.apps.cluster-6fncd.6fncd.sandbox404.opentlc.com
      cors:
        origin: https://rhdh.apps.cluster-6fncd.6fncd.sandbox404.opentlc.com
      reading:
        allow:
          - host: raw.githubusercontent.com
    auth:
      environment: production
      session:
        secret: ${BACKEND_SECRET}
      providers:
        oidc:
          production:
            metadataUrl: "https://keycloak-rhdh-operator.apps.cluster-6fncd.6fncd.sandbox404.opentlc.com/realms/rhdh"
            clientId: rhdh
            clientSecret: developer-hub-secret
            callbackUrl: https://rhdh.apps.cluster-6fncd.6fncd.sandbox404.opentlc.com/api/auth/oidc/handler/frame
            prompt: login
            signIn:
              resolvers:
                - resolver: emailMatchingUserEntityProfileEmail
                  dangerouslyAllowSignInWithoutUserInCatalog: true
      dangerouslyAllowSignInWithoutUserInCatalog: true
    signInPage: oidc
    catalog:
      providers:
        keycloakOrg:
          default:
            baseUrl: "https://keycloak-rhdh-operator.apps.cluster-6fncd.6fncd.sandbox404.opentlc.com"
            loginRealm: "rhdh"
            realm: "rhdh"
            clientId: rhdh
            clientSecret: developer-hub-secret
            schedule:
              frequency: { minutes: 1 }
              timeout: { minutes: 1 }
              initialDelay: { seconds: 15 }
            signIn:
              resolvers:
                - resolver: emailMatchingUserEntityProfileEmail
                  dangerouslyAllowSignInWithoutUserInCatalog: true
    integrations:
      github:
        - host: github.com
          token: ${GITHUB_TOKEN}
    kubernetes:
      serviceLocatorMethod:
        type: 'multiTenant'
      clusterLocatorMethods:
        - type: config
          clusters:
            - name: openshift-cluster
              url: https://api.cluster-6fncd.6fncd.sandbox404.opentlc.com:6443
              authProvider: serviceAccount
              skipTLSVerify: true
              serviceAccountToken: ${K8S_SA_TOKEN}
              customResources:
                - group: 'route.openshift.io'
                  apiVersion: 'v1'
                  plural: 'routes'
    scaffolder:
      github:
        token: ${GITHUB_TOKEN}                    