apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql
  namespace: demo-project
  labels:
    app: postgresql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      containers:
        - name: postgresql
          image: centos/postgresql-12-centos7
          env:
            - name: POSTGRESQL_USER
              value: gitea
            - name: POSTGRESQL_PASSWORD
              value: gitea_password
            - name: POSTGRESQL_DATABASE
              value: gitea
          volumeMounts:
            - name: postgresql-data
              mountPath: /var/lib/pgsql/data
      volumes:
        - name: postgresql-data
          persistentVolumeClaim:
            claimName: postgresql-data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql-data
  namespace: demo-project
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: demo-project
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgresql